services:
  frontend:
    container_name: frontend

    # build with the Dockerfile in this directory
    build:
      context: ./frontend
      args:
        - NODE_ENV=$NODE_ENV

    ports:
      - "5173:5173"

    # when a file changes, sync it to the container
    develop:
      watch:
        - action: sync
          path: .
          target: /app

  # Azure SQL Server from Dockerfile
  azure-sql-edge:
    # image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azure-sql-edge
    networks:
      - azure-sql-edge
    ports:
      - "${MSSQL_SERVER_PORT}:${MSSQL_SERVER_PORT}"
    restart: always

    # build the image
    build:
      context: ./database/azure-sql-edge
      args:
        - ACCEPT_EULA=$ACCEPT_EULA
        - MSSQL_USER=$MSSQL_USER
        - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
        - MSSQL_PID=$MSSQL_PID
        - MSSQL_DATABASE=$MSSQL_DATABASE
        - MSSQL_SERVER_HOST=$MSSQL_SERVER_HOST
        - MSSQL_SERVER_PORT=$MSSQL_SERVER_PORT

    # when a file changes, sync it to the container
    develop:
      watch:
        - action: sync
          path: .
          target: /app

# Azure SQL Server network
networks:
  azure-sql-edge:
    driver: bridge
